ZodiacoFinal/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ZodiacoFinal.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

ZodiacoFinal/Controllers/categoriasController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ZodiacoFinal;

namespace ZodiacoFinal.Controllers
{
    public class categoriasController : Controller
    {
        private BDZodiacoContainer db = new BDZodiacoContainer();

        // GET: categorias
        public ActionResult Index()
        {
            return View(db.categoriaSet.ToList());
        }

        public ActionResult relojeria()
        {
            return View();
        }
        public ActionResult joyeria()
        {
            return View();
        }
        public ActionResult detalle()
        {
            return View();
        }

        // GET: categorias/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            categoria categoria = db.categoriaSet.Find(id);
            if (categoria == null)
            {
                return HttpNotFound();
            }
            return View(categoria);
        }

        // GET: categorias/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: categorias/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Nombre_catg,Descripcion_catg,adicional")] categoria categoria)
        {
            if (ModelState.IsValid)
            {
                db.categoriaSet.Add(categoria);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(categoria);
        }

        // GET: categorias/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            categoria categoria = db.categoriaSet.Find(id);
            if (categoria == null)
            {
                return HttpNotFound();
            }
            return View(categoria);
        }

        // POST: categorias/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Nombre_catg,Descripcion_catg,adicional")] categoria categoria)
        {
            if (ModelState.IsValid)
            {
                db.Entry(categoria).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(categoria);
        }

        // GET: categorias/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            categoria categoria = db.categoriaSet.Find(id);
            if (categoria == null)
            {
                return HttpNotFound();
            }
            return View(categoria);
        }

        // POST: categorias/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            categoria categoria = db.categoriaSet.Find(id);
            db.categoriaSet.Remove(categoria);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ZodiacoFinal/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

ZodiacoFinal/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

ZodiacoFinal/Views/Home/Index.cshtml
@{
    ViewBag.Title = "zodiaco";
}

<section id="myCarousel" class="carousel slide">


    <!-- Indicators -->
    <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
    </ol>
    <!-- Wrapper for slides -->
    <div class="carousel-inner">

        <div class="item active">
            <div class="fill" style="background-image:url('../../Images/carousel/carousel-2.png');"></div>
            <div class="carousel-caption">
            </div>
        </div>
        <div class="item">
            <div class="fill" style="background-image:url('../../Images/carousel/carousel-1.png');"></div>
            <div class="carousel-caption">
            </div>
        </div>
        <div class="item">
            <div class="fill" style="background-image:url('../../Images/carousel/carousel-3.png');"></div>
            <div class="carousel-caption">
            </div>
        </div>
    </div>
    <!-- Controls -->
    <a class="left carousel-control" href="#myCarousel" data-slide="prev">
        <span class="icon-prev"></span>
    </a>
    <a class="right carousel-control" href="#myCarousel" data-slide="next">
        <span class="icon-next"></span>
    </a>
</section>
<section class="featured">

    <div class="container">

        <!-- Header Carousel -->
        <!-- Marketing Icons Section -->
        <div class="row">
            <div class="col-lg-12">
                <h1 class="page-header">
                    Bienvenido a zodiaco<br />
                    <small>     Conoce Nuestro Portafolio de Productos</small>
                </h1>
            </div>
            <div class="col-md-4">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h4><i class="fa fa-fw fa-gift"></i> Joyeria</h4>
                    </div>
                    <div class="panel-body">
                        <p></p>

                        <img class="img-responsive img-portfolio img-hover" src="~/Images/joyeria.jpg" alt="">
                        <br>
                        <p>@Html.ActionLink("¡¡Conoce mas..!!", "joyeria", "categorias", null, htmlAttributes: new { @class = "btn btn-default" })</p>


                    </div>
                </div>
            </div>
            <div class="col-md-4">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h4><i class="fa fa-fw fa-gift"></i> Relojeria</h4>
                    </div>
                    <div class="panel-body">
                        <p></p>
                        <img class="img-responsive img-portfolio img-hover" src="~/Images/relojeria.jpg" alt="">
                        <br>
                        <p>@Html.ActionLink("¡¡Conoce mas..!!", "relojeria", "categorias", null, htmlAttributes: new { @class = "btn btn-default" })</p>

                    </div>
                </div>
            </div>
            <div class="col-md-4">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h4><i class="fa fa-fw fa-gift"></i>Detalles</h4>
                    </div>
                    <div class="panel-body">
                        <p>  </p>
                        <img class="img-responsive img-portfolio img-hover" src="~/Images/detalles.jpg" alt="">
                        <p>Para una ocasion especial, ven a zodiaco, podras encontrar variadad en detalles que deslumbraran</p>
                        <p>@Html.ActionLink("¡¡Conoce mas..!!", "detalle", "categorias", null, htmlAttributes: new { @class = "btn btn-default" })</p>

                    </div>
                </div>
            </div>
        </div>

        <!-- /.row -->
        <hr>
        <!-- Call to Action Section -->
        <div class="well">
            <div class="row">
                <div class="col-md-10">
                    <p>Joyeria zodiaco tiene lo mejor para ti.</p>
                </div>
                <div class="col-md-2">
                    <a class="btn btn-lg  btn-default" href="#">Ve al Inicio</a>
                </div>
            </div>
        </div>
        <hr>

    </div>
</section>